# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fac2bad5d7d692d9b9335b20ede3645422f553ecb5ab3d9db20fcd5f793d256d991bb81f42610657bc53d2295c790ee092b8b082beea30804357ceda95000342

test:
  secret_key_base: 06959e92da8481f1ff6ae894a55c7f98056f41aeadbf01eb2ac030cc88bbf57c138b8b89f1e33a62024b2fe3c57ca04f753e302cf55e19613411b8909625d5ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
